### ISSUE TITLE
Header Ad inserts divs and links into <head>

### ISSUE THREAD

**Issue by jeherve** [Automattic/RadControl#3]
Once you enable the Header ads, `insert_header_ad()` is hooked into `wp_head`, and thus outputs the ad markup inside `head` instead of inside `body`. While the tags are added very late to `wp_head` (priority 100), it still has the potential to break things with other plugins or themes adding things to the `head`, after priority 100.

Would it be possible to hook this inside the body instead?

**Comment by egill** [comment]
This was resolved a while back by fixing the hook being used, changing to wp_head (the one used originally wasn't supposed to be used in this case).
