### ISSUE TITLE
Possible confict with Cloudflare plugin

### ISSUE THREAD

**Issue by garikaib** [Automattic/RadControl#6]
Recently I received an email informing me I was using bots to inflate my page visits and subsequent WordAds earnings after much investigation I can only think of one thing that could have caused this. I recently turned off Cloudflare (about a month ago) but forgot to deactivate or switch off the Cloudflare plugin. I suspect this could have resulted in a false positive.

**Comment by jeherve** [comment]
Could you contact us via this form with more information about your site, so we could look at this with you?
https://wordpress.com/help/contact

Thank you!
